version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fruits
    networks:
      - database_network
    deploy:
      replicas: 1

  quarkusservice:
    image: motyim/quarkus-crud-demo:firsttry
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://db:5432/fruits'
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    networks:
      - database_network
    deploy:
      replicas: 1

networks:
  database_network:
    driver: overlay
